#define SYSTICKS_PER_SECOND 100
#define SYSTICK_PERIOD_MS (1000 / SYSTICKS_PER_SECOND)

#define STACK_SIZE 1000
#define HEAP_SIZE 1000

#define DIAGNOSTIC_PUB

#ifdef DIAGNOSTIC_PUB
#define DIAGNOSTIC_PUB_HANDLE 1
#else
#define DIAGNOSTIC_PUB_HANDLE 0
#endif
