name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      os:
        description: "The OS to use for the workflow"
        required: true
        type: string
      branch:
        description: "The branch to use for the workflow"
        required: true
        type: string
      python-version:
        description: "The Python version to use for the workflow"
        required: false
        type: string
        default: "3.12"

jobs:
  build:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
    steps:

      - name: Sync repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Install APT packages
        uses: ./.github/actions/install_apt_packages
        with:
          packages: "build-essential cmake gcc-arm-none-eabi rsync"
          use-sudo: "true"
          use-update: "true"

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install required python packages
        uses: ./.github/actions/install_python_packages
        with:
<<<<<<< HEAD
          packages: "catkin_pkg lark-parser empy colcon-common-extensions"
=======
          requirements-file: "${{ github.workspace }}/requirements.txt"
>>>>>>> 0ca6886 (Add requirements.txt file for Python dependencies (#40))
          python-version: ${{ inputs.python-version }}
          use-sudo: "true"

      - name: Install TivaWare SDK
        uses: ./.github/actions/install_sdk
        with:
          sdk_version: "2.1.4.178"
          install_path: "${{ github.workspace }}/tivaware_c_series"
          force_reinstall: "false"
          use-sudo: "true"

      - name: Build project
        run: make -j$(nproc)
        shell: bash
