name: Reusable CI Workflow

on:
  workflow_call:
    inputs:
      os:
        description: "The OS to use for the workflow"
        required: true
        type: string
      branch:
        description: "The branch to use for the workflow"
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
    steps:

      - name: Sync repository
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
          submodules: recursive

      - name: Install APT packages
        uses: ./.github/actions/install_apt_packages
        with:
          packages: "build-essential cmake gcc-arm-none-eabi rsync"
          use-sudo: "true"
          use-update: "true"

      - name: Setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: Install required python packages
        uses: ./.github/actions/install_python_packages
        with:
          packages: "catkin_pkg lark-parser empy==3.3.4 colcon-common-extensions"
          python-version: "3.10"
          use-sudo: "true"

      - name: Install TivaWare SDK
        uses: ./.github/actions/install_sdk
        with:
          sdk_version: "2.1.4.178"
          install_path: "${{ github.workspace }}/tivaware_c_series"
          force_reinstall: "false"
          use-sudo: "true"

      - name: Build project
        run: make -j$(nproc)
        shell: bash
